In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import cross_val_score

In [2]:
data = pd.read_csv('default of credit card clients.csv', header=1)
data.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1      20000    2          2         1   24      2      2     -1     -1   
1   2     120000    2          2         2   26     -1      2      0      0   
2   3      90000    2          2         2   34      0      0      0      0   
3   4      50000    2          2         1   37      0      0      0      0   
4   5      50000    1          2         1   57     -1      0     -1      0   

              ...              BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  \
0             ...                      0          0          0         0   
1             ...                   3272       3455       3261         0   
2             ...                  14331      14948      15549      1518   
3             ...                  28314      28959      29547      2000   
4             ...                  20940      19146      19131      2000   

   PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
0       689         0         0         0         0   
1      1000      1000      1000         0      2000   
2      1500      1000      1000      1000      5000   
3      2019      1200      1100      1069      1000   
4     36681     10000      9000       689       679   

   default payment next month  
0                           1  
1                           1  
2                           0  
3                           0  
4                           0  

[5 rows x 25 columns]

In [3]:
k = data.columns
k

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month'],
      dtype='object')

In [4]:
X = data.iloc[:,:-1].values
y = data.iloc[:,24].values

In [5]:
data.shape

(30000, 25)

In [6]:
import statsmodels.formula.api as sm
X = np.append(arr=np.ones((30000,1)).astype(int), values=X, axis=1)
X

array([[     1,      1,  20000, ...,      0,      0,      0],
       [     1,      2, 120000, ...,   1000,      0,   2000],
       [     1,      3,  90000, ...,   1000,   1000,   5000],
       ...,
       [     1,  29998,  30000, ...,   4200,   2000,   3100],
       [     1,  29999,  80000, ...,   1926,  52964,   1804],
       [     1,  30000,  50000, ...,   1000,   1000,   1000]], dtype=int64)

In [7]:
X_opt = X[:, [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24]]
reg_ols = sm.OLS(endog=y, exog=X_opt).fit() 
reg_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.124
Model:                            OLS   Adj. R-squared:                  0.123
Method:                 Least Squares   F-statistic:                     176.8
Date:                Thu, 31 May 2018   Prob (F-statistic):               0.00
Time:                        08:47:03   Log-Likelihood:                -14202.
No. Observations:               30000   AIC:                         2.845e+04
Df Residuals:                   29975   BIC:                         2.866e+04
Df Model:                          24                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.3151      0.018     17.245      0.000       0.279       0.351
x1         -6.681e-08   2.61e-07     -0.256      0.798   -5.78e-07    4.45e-07
x2         -9.046e-08   2.16e-08     -4.190      0.000   -1.33e-07   -4.81e-08
x3            -0.0145      0.005     -3.126      0.002      -0.024      -0.005
x4            -0.0151      0.003     -5.007      0.000      -0.021      -0.009
x5            -0.0238      0.005     -5.000      0.000      -0.033      -0.014
x6             0.0014      0.000      5.128      0.000       0.001       0.002
x7             0.0957      0.003     34.575      0.000       0.090       0.101
x8             0.0195      0.003      5.831      0.000       0.013       0.026
x9             0.0117      0.004      3.250      0.001       0.005       0.019
x10            0.0034      0.004      0.855      0.393      -0.004       0.011
x11            0.0057      0.004      1.316      0.188      -0.003       0.014
x12            0.0008      0.004      0.224      0.822      -0.006       0.008
x13        -6.224e-07   1.14e-07     -5.453      0.000   -8.46e-07   -3.99e-07
x14          1.58e-07    1.6e-07      0.985      0.325   -1.56e-07    4.72e-07
x15          3.02e-08   1.51e-07      0.200      0.841   -2.66e-07    3.26e-07
x16        -6.503e-08   1.58e-07     -0.412      0.680   -3.74e-07    2.44e-07
x17        -2.294e-08   1.85e-07     -0.124      0.901   -3.85e-07    3.39e-07
x18         1.155e-07   1.46e-07      0.791      0.429   -1.71e-07    4.02e-07
x19        -7.436e-07   1.77e-07     -4.200      0.000   -1.09e-06   -3.97e-07
x20        -2.098e-07   1.46e-07     -1.440      0.150   -4.95e-07    7.57e-08
x21         -2.83e-08   1.69e-07     -0.168      0.867   -3.59e-07    3.03e-07
x22        -2.504e-07   1.84e-07     -1.361      0.174   -6.11e-07     1.1e-07
x23        -3.417e-07   1.91e-07     -1.791      0.073   -7.16e-07    3.23e-08
x24        -9.802e-08   1.37e-07     -0.718      0.473   -3.66e-07     1.7e-07
==============================================================================
Omnibus:                     4681.677   Durbin-Watson:                   2.013
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             7284.526
Skew:                           1.204   Prob(JB):                         0.00
Kurtosis:                       3.178   Cond. No.                     2.15e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.15e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [8]:
# 2,13,16,18,22,17,11

In [9]:
X_opt = X[:, [0,1,3,4,5,6,7,8,9,10,12,14,15,20,21,23,24]]
reg_ols = sm.OLS(endog=y, exog=X_opt).fit() 
reg_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.122
Model:                            OLS   Adj. R-squared:                  0.122
Method:                 Least Squares   F-statistic:                     260.7
Date:                Thu, 31 May 2018   Prob (F-statistic):               0.00
Time:                        08:47:03   Log-Likelihood:                -14234.
No. Observations:               30000   AIC:                         2.850e+04
Df Residuals:                   29983   BIC:                         2.864e+04
Df Model:                          16                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.3004      0.018     16.658      0.000       0.265       0.336
x1         -1.091e-07    2.6e-07     -0.419      0.675   -6.19e-07    4.01e-07
x2            -0.0147      0.005     -3.172      0.002      -0.024      -0.006
x3            -0.0122      0.003     -4.170      0.000      -0.018      -0.006
x4            -0.0221      0.005     -4.653      0.000      -0.031      -0.013
x5             0.0013      0.000      4.598      0.000       0.001       0.002
x6             0.0970      0.003     35.179      0.000       0.092       0.102
x7             0.0208      0.003      6.315      0.000       0.014       0.027
x8             0.0130      0.004      3.655      0.000       0.006       0.020
x9             0.0068      0.003      1.939      0.053   -7.35e-05       0.014
x10            0.0044      0.003      1.507      0.132      -0.001       0.010
x11         -5.94e-07   1.05e-07     -5.640      0.000      -8e-07   -3.88e-07
x12         8.992e-08   1.13e-07      0.795      0.427   -1.32e-07    3.12e-07
x13        -4.129e-07   1.32e-07     -3.139      0.002   -6.71e-07   -1.55e-07
x14        -2.234e-07   1.38e-07     -1.614      0.107   -4.95e-07    4.79e-08
x15        -4.273e-07   1.53e-07     -2.790      0.005   -7.28e-07   -1.27e-07
x16        -2.909e-07   1.31e-07     -2.212      0.027   -5.49e-07   -3.32e-08
==============================================================================
Omnibus:                     4717.960   Durbin-Watson:                   2.013
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             7362.837
Skew:                           1.210   Prob(JB):                         0.00
Kurtosis:                       3.186   Cond. No.                     9.87e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.87e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_opt, y, test_size= 0.2, random_state = 0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.fit_transform(X_test)

C:\Users\tabme\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [12]:
from sklearn.linear_model import LogisticRegression 
clf = LogisticRegression(random_state= 0)
clf.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [13]:
y_pred = clf.predict(X_test)

In [14]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[4593,  110],
       [ 983,  314]], dtype=int64)

In [15]:
accuracy = cross_val_score(clf, X_train, y_train, cv=10, scoring='accuracy')
precision = cross_val_score(clf, X_train, y_train, cv=10, scoring='precision')
recall = cross_val_score(clf, X_train, y_train, cv=10, scoring='recall')
f1 = cross_val_score(clf, X_train, y_train, cv=10, scoring='f1')
print(accuracy.mean())
print(precision.mean())
print(recall.mean())
print(f1.mean())

0.8075421114005403
0.7074578366438204
0.23113251962251685
0.3481463951146958


In [16]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [17]:
y_pred = classifier.predict(X_test)

In [18]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[4325,  378],
       [ 820,  477]], dtype=int64)

In [19]:
accuracy = cross_val_score(classifier, X_train, y_train, cv=10, scoring='accuracy')
precision = cross_val_score(classifier, X_train, y_train, cv=10, scoring='precision')
recall = cross_val_score(classifier, X_train, y_train, cv=10, scoring='recall')
f1 = cross_val_score(classifier, X_train, y_train, cv=10, scoring='f1')
print(accuracy.mean())
print(precision.mean())
print(recall.mean())
print(f1.mean())

0.7943337080874493
0.5597381951585212
0.35194011706754924
0.43198806496290854


In [20]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=0, shrinking=True,
  tol=0.001, verbose=False)

In [21]:
y_pred = classifier.predict(X_test)

In [22]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[4594,  109],
       [ 986,  311]], dtype=int64)

In [23]:
accuracy = cross_val_score(classifier, X_train, y_train, cv=10, scoring='accuracy')
precision = cross_val_score(classifier, X_train, y_train, cv=10, scoring='precision')
recall = cross_val_score(classifier, X_train, y_train, cv=10, scoring='recall')
f1 = cross_val_score(classifier, X_train, y_train, cv=10, scoring='f1')
print(accuracy.mean())
print(precision.mean())
print(recall.mean())
print(f1.mean())

0.8067503058449607
0.6987805508968629
0.2320684978673469
0.34824682254105677


In [24]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=0, shrinking=True,
  tol=0.001, verbose=False)

In [25]:
y_pred = classifier.predict(X_test)

In [26]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[4503,  200],
       [ 845,  452]], dtype=int64)

In [27]:
accuracy = cross_val_score(classifier, X_train, y_train, cv=10, scoring='accuracy')
precision = cross_val_score(classifier, X_train, y_train, cv=10, scoring='precision')
recall = cross_val_score(classifier, X_train, y_train, cv=10, scoring='recall')
f1 = cross_val_score(classifier, X_train, y_train, cv=10, scoring='f1')
print(accuracy.mean())
print(precision.mean())
print(recall.mean())
print(f1.mean())

0.8192504450666283
0.6919027945577455
0.3384545115978385
0.45436091196991946


In [28]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None)

In [29]:
y_pred = classifier.predict(X_test)

In [30]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[3965,  738],
       [ 586,  711]], dtype=int64)

In [31]:
accuracy = cross_val_score(classifier, X_train, y_train, cv=10, scoring='accuracy')
precision = cross_val_score(classifier, X_train, y_train, cv=10, scoring='precision')
recall = cross_val_score(classifier, X_train, y_train, cv=10, scoring='recall')
f1 = cross_val_score(classifier, X_train, y_train, cv=10, scoring='f1')
print(accuracy.mean())
print(precision.mean())
print(recall.mean())
print(f1.mean())

0.7733750442202044
0.4918140629932083
0.5587206891947917
0.5230423154805981


In [32]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [33]:
y_pred = classifier.predict(X_test)

In [34]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[3780,  923],
       [ 759,  538]], dtype=int64)

In [35]:
accuracy = cross_val_score(classifier, X_train, y_train, cv=10, scoring='accuracy')
precision = cross_val_score(classifier, X_train, y_train, cv=10, scoring='precision')
recall = cross_val_score(classifier, X_train, y_train, cv=10, scoring='recall')
f1 = cross_val_score(classifier, X_train, y_train, cv=10, scoring='f1')
print(accuracy.mean())
print(precision.mean())
print(recall.mean())
print(f1.mean())

0.7255420215495407
0.38718517147176384
0.3998882728671712
0.39326857199113774


In [36]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [37]:
y_pred = classifier.predict(X_test)

In [38]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[4503,  200],
       [ 851,  446]], dtype=int64)

In [39]:
accuracy = cross_val_score(classifier, X_train, y_train, cv=10, scoring='accuracy')
precision = cross_val_score(classifier, X_train, y_train, cv=10, scoring='precision')
recall = cross_val_score(classifier, X_train, y_train, cv=10, scoring='recall')
f1 = cross_val_score(classifier, X_train, y_train, cv=10, scoring='f1')
print(accuracy.mean())
print(precision.mean())
print(recall.mean())
print(f1.mean())

0.8150424241176083
0.6496005234672505
0.3663634574980149
0.46830663544101947
